### ISSUE TITLE
How to force exit?

### ISSUE THREAD

**Issue by moduspwnens** [zalando-incubator/kopf#231]
I'm using kopf for a Kubernetes controller project and one of the things I'm expecting it to do is exit with a non-zero exit code if certain conditions are met. This will cause the pod to get restarted and another process will resolve the condition.

Normally I'd do this with `sys.exit(1)` or `raise SystemExit`, but those don't seem to work. I'm not sure what state it gets in, but it doesn't exit. I've got a few ways I can work around this, but since you already have the concept of different error types that lead to different behaviors by kopf, it'd be cool to have another error type to signal to kopf that I want the whole process to exit with a certain error code.

**Comment by nolar** [comment]
@moduspwnens Can you please clarify which version of Kopf do you use? And how do you check that it does not exit? I.e., does it freeze on exit with no activities happening, or it says they was a `SystemExit` exception, and silences it silently?

**Comment by moduspwnens** [comment]
Sorry--I saw this as more of a feature request than a bug report, so I didn't include bug report details.

I was using version 0.22, but as part of verifying steps to recreate the issue for this comment, I tried version 0.23 instead and it's working as expected there. When I do `sys.exit(1)`, it exits immediately with the exit code I specify. So it seems to be working for me now. Thanks!

**Comment by nolar** [comment]
I see. Such exiting was never a tested or specially designed behaviour. Therefore, I didn't know how it will behave with `SystemExit` raised in a threaded handler — will it escalate, or will it be suppressed.

But since it works now, it could also be caused by #142 — an improper process termination. I.e., it actually exited the operator previously on `SystemExit`, but was freezing at the after-exit cleanups (children threads waiting).
