### ISSUE TITLE
Question : Writing to API

### ISSUE THREAD

**Issue by grzesuav** [zalando-incubator/kopf#259]
## Expected Behavior

Hi, I am looking for a way to handle writing object to kubernetes API (create/update) based not on observed objects but rather on disk configuration.

## Actual Behavior

Cannot find a way to do it, seems like kopf reacts on events triggered by kubernetes

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

I generate some kubernetes manifests I would like to apply , without manually checking if given resource exists, update version etc.

**Comment by nolar** [comment]
@grzesuav Can you please provide an example? I do not understand what is a "disk configuration" in this case.

**Comment by grzesuav** [comment]
Sure, I have some json file in dockerimage which I would like to use as a source to generate `PrometheusRule` object without worrying about object existence, etc

**Comment by grzesuav** [comment]
Main point is it isn't triggered by any other event from kubernetes API

**Comment by nolar** [comment]
Maybe I still do not understand it, but it looks like a job of a Kubernetes API client library, not of the the operator framework.

You can read the JSON, render the template or substitute the variables, and apply the resulting object to the API. You can see examples here (just with YAML and an inline template rather than a file): 

* https://github.com/zalando-incubator/kopf/blob/master/examples/02-children/example.py —  the `kubernetes` client library. 
* https://github.com/zalando-incubator/kopf/blob/master/examples/99-all-at-once/example.py#L100-L116 — with `pykube-ng`

Kopf is not a client library, it is an operator framework. As such, it does not dictate how the objects are created/updated/applied, and does not provide any means to do that. In fact, it _intentionally_ [remains client-agnostic](https://kopf.readthedocs.io/en/latest/hierarchies/), allowing the developers to use their preferred client library.

So, answering your question, maybe it should be tried with one of those client libraries?

**Comment by grzesuav** [comment]
@nolar actually I started from using kubernetes python client, and it is simply too complicated - I would like to have simplicity of `kubectl apply ` but I end up with :
* checking if given object exist (different command for create new and update)
* increasing version
+ several other cases, and for my usage it was simply overkill. Looking at what kopf is doing I believe it handles this right way. 


Thank for your answer. and for mentioning https://pypi.org/project/pykube-ng/, I haven't use it  so Iwill give it a try.


Cheers !

**Comment by nolar** [comment]
@grzesuav Then take a look at the declarative commands of `kubectl` (specifically, `kubectl apply`): https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/ — this is what you are looking for.
