### ISSUE TITLE
Change the handler filter dynamically

### ISSUE THREAD

**Issue by zasherif** [zalando-incubator/kopf#324]
First of all, thanks for the fantastic framework!

## Long story short

Let's say I have a handler that filters object, How can I change the filter dynamically within the handler logic?

## Description

Consider this example:
```
@kopf.on.create('zalando.org', 'v1', 'kopfexamples', labels={'somelabel': 'somevalue'})
def my_handler(spec, **_):
    pass
```

The labels are static 'somelabel': 'somevalue'. It would be great to have an interface that easily change the filter. For example:

```
@kopf.on.create('zalando.org', 'v1', 'kopfexamples', labels={'somelabel': 'somevalue'})
def my_handler(spec, **_):
    # Do some logic
    kopf.reset.create(my_handler, 'zalando.org', 'v1', 'kopfexamples', labels={'somelabel': 'newvalue'})
```

Is that plausible? Can I achieve the same outcome with existing interfaces (e.g. subhandlers, or not using decorators)

**Comment by michaelnarodovitch** [comment]
Hey, maybe you have a chance by using an arbitrary callback and changing that dynamically?

```
my_filter_func = lambda labels, **_: labels['somelabel'] == 'somevalue'

@kopf.on.create('zalando.org', 'v1', 'kopfexamples', when=my_filter_func)
def my_handler(spec, **_):
    global my_filter_func
    my_filter_func = lambda labels, **_: labels['somelabel'] == 'newvalue'
```

I didn't try it, but I am curious if it works. I expect so, as the `my_filter_func` callback seems to be mutable. See https://kopf.readthedocs.io/en/latest/filters/ for ref.

**Comment by nolar** [comment]
Please note that in @michaelnarodovitch's solution, the `my_filter_func` is remembered in the handler at the moment of registration. Any future changes of a global `my_filter_func` variable will not be reflected in the handler. If you want to follow that way and have the global filter change for all the resources, use `when=lambda **kwargs: my_filter_func(**kwargs)` — it will use the current function's body on every call, rather the initially defined one.

It is the same trick as with the function's mutable defaults in Python, which are shared across the function calls, since they are created and remembered at the time of declaration, not at the time of use.

---

If you want to alter the filters on a per-resource basis, you can also use per-object `memo` kwarg to store any arbitrary values and share it between handlers & callbacks (which has both [object's and dict's interfaces](https://github.com/zalando-incubator/kopf/blob/0.27rc2/kopf/structs/containers.py#L39) for same-named fields-attrs).

```python
import kopf

def is_suitable(memo, labels, **_):
    return labels.get('somelabel') == memo.get('label_filter', 'somevalue')

@kopf.on.create('zalando.org', 'v1', 'kopfexamples', when=is_suitable)
def my_handler(spec, memo, **_):
    memo['label_filter'] = 'newvalue'
```

Similarly, labels' and annotations' filtering criteria can be also the callbacks (beside `kopf.ABSENT` and `kopf.PRESENT` tokens):

```python
import kopf

@kopf.on.create('zalando.org', 'v1', 'kopfexamples', 
                labels={'somelabel': lambda value, memo, **_: value == memo.get('label_filter', 'somevalue')})
def my_handler(spec, memo, **_):
    memo['label_filter'] = 'newvalue'
```

Whatever looks better for you.

Requires `kopf>=0.27rc1` (as of 2020-04-07; see the [release notes](https://github.com/zalando-incubator/kopf/releases)).

Docs:

* https://kopf.readthedocs.io/en/latest/filters/#by-arbitrary-callbacks

---

@zasherif I hope, these tricks answer your question. If not, please clarify the use-case and re-open this issue.
