### ISSUE TITLE
kopf disallow importing modules on path

### ISSUE THREAD

**Issue by trondhindenes** [zalando-incubator/kopf#92]
Given the following app structure:
```
╰─ cat app.py 
import kopf
import json

from MyMod.lib1 import Lib1
l = Lib1

@kopf.on.create('testing.com', 'v1', 'mycrd')
def create_fn(body, **kwargs):
    print(f'A handler is called with body: {json.dumps(body, indent=4, sort_keys=True)}')
```
```
╰─ ls MyMod 
__init__.py  lib1.py
```

```
╰─ cat MyMod/lib1.py 
class Lib1:
    def __init__():
        pass
    def doit(what):
        pass
```

In other words, in the app dir, I have a regular python module

If I execute the app.py file with regular Python, it just exits (as is expected), without throwing any error, meaning that all the imports work as expected.

However, if I run `pipenv run kopf run app.py`, it throws `ModuleNotFoundError: No module named 'MyMod'`.

## Expected Behavior
apps run using kopf should be able to import local modules just fine

## Actual Behavior
kopf throws (see above

## Steps to Reproduce the Problem
in a blank dir:
```
pip install pipenv
PIPENV_VENV_IN_PROJECT=true pipenv install --dev --python python3.7
```
create files as described above
`pipenv run kopf run app.py`
## Specifications

  - Platform:
  - Kubernetes version: *(use `kubectl version`)*
  - Python version: *(use `python --version`)*
  - Python packages installed: *(use `pip freeze --all`)*

```
```

**Comment by trondhindenes** [comment]
as far as I can see, all that's missing is adding `curdir`to sys.path prior to loading.

**Comment by nolar** [comment]
@trondhindenes Thanks for detailed report.

Kopf uses the standard Python's importing system and does not hack the Python's importing mechanics, as it can affect different projects with different layouts in differently ways — and this importing logic falls out of scope of a Kubernetes operator framework. 

Putting the current script's dir (but not the current work dir!) to `sys.path` is one of the Python's default tricks, as officially documented. Since the current script is `kopf` from the virtualenv's `bin` directory, this is not much helpful.

The easiest way you can try to use is to hack the importing paths with [`PYTHONPATH`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) env var:

```bash
PYTHONPATH=/home/$USER/src/myproj/  pipenv run kopf run ...
# OR:
PYTHONPATH=.  pipenv run kopf run ...
```

Another way is to hack [`sys.path`](https://docs.python.org/3/library/sys.html#sys.path) in the beginning of `app.py`:

```python
import sys
sys.path.insert(0, os.path.dirname(__file__))

from MyMod.lib1 import Lib1
```

If you have a complex system of modules in your application, you can also put `app.py` into one of your importable/installable packages, and to use this [official Kopf's feature](https://kopf.readthedocs.io/en/stable/loading/):

```
kopf run -m MyMod.app
```

In that case, the handlers module will be loaded as if by `import MyMod.app` (similar to `python -m` semantics). 

However, you still have to make the modules importable without the Python's "current dir magic" — with one of the above methods, or by packaging your app the standard Python ways (`setup.py`, `pip install -e .`, etc).

Please let me know if any of these hints helped.

**Comment by trondhindenes** [comment]
yup, definitely not a problem with using either `PYTHONPATH` or `sys.path` hacking in app code - it just feels like it would be more "pythonic" if kopf handled that more gracefully by default. But no biggie.
